import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class ScratchGameData {
  List<IconData> logos;
  final IconData correctLogo;
  final String instructions;

  ScratchGameData({this.logos, this.correctLogo, this.instructions});

  static final List<ScratchGameData> list = [
    ScratchGameData(
      logos: [
        FontAwesomeIcons.snapchat,
        FontAwesomeIcons.instagram,
        FontAwesomeIcons.facebookF,
        FontAwesomeIcons.instagram,
        FontAwesomeIcons.google,
        FontAwesomeIcons.google,
        FontAwesomeIcons.snapchat,
        FontAwesomeIcons.twitter,
        FontAwesomeIcons.twitter,
      ],
      correctLogo: FontAwesomeIcons.facebookF,
      instructions: 'Find Facebook logo',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.moneyBillAlt,
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.thumbsDown,
        FontAwesomeIcons.thumbsDown,
      ],
      correctLogo: FontAwesomeIcons.moneyBillAlt,
      instructions: 'Find Lottery Ticket',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.church,
        FontAwesomeIcons.city,
        FontAwesomeIcons.dungeon,
        FontAwesomeIcons.store,
        FontAwesomeIcons.warehouse,
        FontAwesomeIcons.university,
        FontAwesomeIcons.hospital,
        FontAwesomeIcons.home,
        FontAwesomeIcons.kaaba,
      ],
      correctLogo: FontAwesomeIcons.church,
      instructions: 'Find Church',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.compressAlt,
        FontAwesomeIcons.compressArrowsAlt,
        FontAwesomeIcons.longArrowAltUp,
        FontAwesomeIcons.longArrowAltDown,
        FontAwesomeIcons.longArrowAltLeft,
        FontAwesomeIcons.longArrowAltRight,
        FontAwesomeIcons.expandAlt,
        FontAwesomeIcons.sortAlphaUp,
        FontAwesomeIcons.sortAlphaDown,
      ],
      correctLogo: FontAwesomeIcons.longArrowAltUp,
      instructions: 'Find Up Arrow',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.plug,
        FontAwesomeIcons.plug,
        FontAwesomeIcons.gem,
        FontAwesomeIcons.flag,
        FontAwesomeIcons.flag,
        FontAwesomeIcons.wrench,
        FontAwesomeIcons.wrench,
        FontAwesomeIcons.sortAlphaUp,
        FontAwesomeIcons.sortAlphaDown,
      ],
      correctLogo: FontAwesomeIcons.gem,
      instructions: 'Find a Diamond',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.android,
        FontAwesomeIcons.android,
        FontAwesomeIcons.blackberry,
        FontAwesomeIcons.blackberry,
        FontAwesomeIcons.chrome,
        FontAwesomeIcons.apple,
        FontAwesomeIcons.chrome,
        FontAwesomeIcons.discord,
        FontAwesomeIcons.discord,
      ],
      correctLogo: FontAwesomeIcons.apple,
      instructions: 'Find Apple logo',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.donate,
        FontAwesomeIcons.donate,
        FontAwesomeIcons.grimace,
        FontAwesomeIcons.grimace,
        FontAwesomeIcons.bitcoin,
        FontAwesomeIcons.wifi,
        FontAwesomeIcons.wifi,
        FontAwesomeIcons.coins,
        FontAwesomeIcons.coins,
      ],
      correctLogo: FontAwesomeIcons.bitcoin,
      instructions: 'Find Bitcoin',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.dog,
        FontAwesomeIcons.dog,
        FontAwesomeIcons.crow,
        FontAwesomeIcons.crow,
        FontAwesomeIcons.cat,
        FontAwesomeIcons.cat,
        FontAwesomeIcons.horse,
        FontAwesomeIcons.horse,
        FontAwesomeIcons.dragon,
      ],
      correctLogo: FontAwesomeIcons.dragon,
      instructions: 'Find dragon',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.otter,
        FontAwesomeIcons.otter,
        FontAwesomeIcons.kiwiBird,
        FontAwesomeIcons.kiwiBird,
        FontAwesomeIcons.frog,
        FontAwesomeIcons.frog,
        FontAwesomeIcons.spider,
        FontAwesomeIcons.hippo,
        FontAwesomeIcons.hippo,
      ],
      correctLogo: FontAwesomeIcons.spider,
      instructions: 'Find spider',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.appleAlt,
        FontAwesomeIcons.appleAlt,
        FontAwesomeIcons.carrot,
        FontAwesomeIcons.carrot,
        FontAwesomeIcons.leaf,
        FontAwesomeIcons.leaf,
        FontAwesomeIcons.pepperHot,
        FontAwesomeIcons.pepperHot,
        FontAwesomeIcons.lemon,
      ],
      correctLogo: FontAwesomeIcons.lemon,
      instructions: 'Find lemon',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.dizzy,
        FontAwesomeIcons.dizzy,
        FontAwesomeIcons.flushed,
        FontAwesomeIcons.flushed,
        FontAwesomeIcons.angry,
        FontAwesomeIcons.frown,
        FontAwesomeIcons.frown,
        FontAwesomeIcons.grimace,
        FontAwesomeIcons.grimace,
      ],
      correctLogo: FontAwesomeIcons.angry,
      instructions: 'Find angry Emoji',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.divide,
        FontAwesomeIcons.divide,
        FontAwesomeIcons.infinity,
        FontAwesomeIcons.infinity,
        FontAwesomeIcons.minus,
        FontAwesomeIcons.minus,
        FontAwesomeIcons.calculator,
        FontAwesomeIcons.plus,
        FontAwesomeIcons.plus,
      ],
      correctLogo: FontAwesomeIcons.calculator,
      instructions: 'Find calculator',
    ),
    ScratchGameData(
      logos: [
        FontAwesomeIcons.ambulance,
        FontAwesomeIcons.babyCarriage,
        FontAwesomeIcons.babyCarriage,
        FontAwesomeIcons.bicycle,
        FontAwesomeIcons.bicycle,
        FontAwesomeIcons.bus,
        FontAwesomeIcons.bus,
        FontAwesomeIcons.helicopter,
        FontAwesomeIcons.helicopter,
      ],
      correctLogo: FontAwesomeIcons.ambulance,
      instructions: 'Find ambulance',
    ),
  ];
}
